blank_issues_enabled: false
contact_links:
  - name: Documentation request
    url: https://github.com/streamlit/docs/issues/new/choose
    about: Let us know how our docs could be better
  - name: Streamlit documentation
    url: https://docs.streamlit.io/
    about: Learn more about how to use Streamlit
  - name: Anything else?
    url: https://discuss.streamlit.io/
    about: Ask usage questions on the Streamlit community forum
